// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/dungeon.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DungeonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonRequest) Reset() {
	*x = DungeonRequest{}
	mi := &file_proto_dungeon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonRequest) ProtoMessage() {}

func (x *DungeonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonRequest.ProtoReflect.Descriptor instead.
func (*DungeonRequest) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{0}
}

func (x *DungeonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DungeonRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DungeonRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type DungeonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonResponse) Reset() {
	*x = DungeonResponse{}
	mi := &file_proto_dungeon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonResponse) ProtoMessage() {}

func (x *DungeonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonResponse.ProtoReflect.Descriptor instead.
func (*DungeonResponse) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{1}
}

func (x *DungeonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DungeonResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DungeonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DungeonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DungeonResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DungeonAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonAck) Reset() {
	*x = DungeonAck{}
	mi := &file_proto_dungeon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonAck) ProtoMessage() {}

func (x *DungeonAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonAck.ProtoReflect.Descriptor instead.
func (*DungeonAck) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{2}
}

func (x *DungeonAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DungeonCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	DropId        string                 `protobuf:"bytes,3,opt,name=drop_id,json=dropId,proto3" json:"drop_id,omitempty"`
	ChestId       string                 `protobuf:"bytes,4,opt,name=chest_id,json=chestId,proto3" json:"chest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonCommand) Reset() {
	*x = DungeonCommand{}
	mi := &file_proto_dungeon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonCommand) ProtoMessage() {}

func (x *DungeonCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonCommand.ProtoReflect.Descriptor instead.
func (*DungeonCommand) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{3}
}

func (x *DungeonCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DungeonCommand) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *DungeonCommand) GetDropId() string {
	if x != nil {
		return x.DropId
	}
	return ""
}

func (x *DungeonCommand) GetChestId() string {
	if x != nil {
		return x.ChestId
	}
	return ""
}

type DungeonCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Command       *DungeonCommand        `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonCommandRequest) Reset() {
	*x = DungeonCommandRequest{}
	mi := &file_proto_dungeon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonCommandRequest) ProtoMessage() {}

func (x *DungeonCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonCommandRequest.ProtoReflect.Descriptor instead.
func (*DungeonCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{4}
}

func (x *DungeonCommandRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DungeonCommandRequest) GetCommand() *DungeonCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type DungeonCommandRelay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Command       *DungeonCommand        `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonCommandRelay) Reset() {
	*x = DungeonCommandRelay{}
	mi := &file_proto_dungeon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonCommandRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonCommandRelay) ProtoMessage() {}

func (x *DungeonCommandRelay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonCommandRelay.ProtoReflect.Descriptor instead.
func (*DungeonCommandRelay) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{5}
}

func (x *DungeonCommandRelay) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DungeonCommandRelay) GetCommand() *DungeonCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type DungeonSnapshot struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Slot                     uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	X                        float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                        float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Hp                       int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp                    int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Facing                   string                 `protobuf:"bytes,6,opt,name=facing,proto3" json:"facing,omitempty"`
	Moving                   bool                   `protobuf:"varint,7,opt,name=moving,proto3" json:"moving,omitempty"`
	Attacking                bool                   `protobuf:"varint,8,opt,name=attacking,proto3" json:"attacking,omitempty"`
	Dead                     bool                   `protobuf:"varint,9,opt,name=dead,proto3" json:"dead,omitempty"`
	LastAttackElapsedMs      float64                `protobuf:"fixed64,10,opt,name=last_attack_elapsed_ms,json=lastAttackElapsedMs,proto3" json:"last_attack_elapsed_ms,omitempty"`
	LastContactElapsedMs     float64                `protobuf:"fixed64,11,opt,name=last_contact_elapsed_ms,json=lastContactElapsedMs,proto3" json:"last_contact_elapsed_ms,omitempty"`
	SkillCooldownRemainingMs map[string]float64     `protobuf:"bytes,12,rep,name=skill_cooldown_remaining_ms,json=skillCooldownRemainingMs,proto3" json:"skill_cooldown_remaining_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	HasteRemainingMs         float64                `protobuf:"fixed64,13,opt,name=haste_remaining_ms,json=hasteRemainingMs,proto3" json:"haste_remaining_ms,omitempty"`
	HealthPotions            int32                  `protobuf:"varint,14,opt,name=health_potions,json=healthPotions,proto3" json:"health_potions,omitempty"`
	// Durable state is kept as a JSON value because equipment and modifiers are
	// extensible gameplay data. The envelope and transport remain protobuf.
	StateJson     string `protobuf:"bytes,15,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonSnapshot) Reset() {
	*x = DungeonSnapshot{}
	mi := &file_proto_dungeon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonSnapshot) ProtoMessage() {}

func (x *DungeonSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonSnapshot.ProtoReflect.Descriptor instead.
func (*DungeonSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{6}
}

func (x *DungeonSnapshot) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DungeonSnapshot) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DungeonSnapshot) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DungeonSnapshot) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *DungeonSnapshot) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *DungeonSnapshot) GetFacing() string {
	if x != nil {
		return x.Facing
	}
	return ""
}

func (x *DungeonSnapshot) GetMoving() bool {
	if x != nil {
		return x.Moving
	}
	return false
}

func (x *DungeonSnapshot) GetAttacking() bool {
	if x != nil {
		return x.Attacking
	}
	return false
}

func (x *DungeonSnapshot) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *DungeonSnapshot) GetLastAttackElapsedMs() float64 {
	if x != nil {
		return x.LastAttackElapsedMs
	}
	return 0
}

func (x *DungeonSnapshot) GetLastContactElapsedMs() float64 {
	if x != nil {
		return x.LastContactElapsedMs
	}
	return 0
}

func (x *DungeonSnapshot) GetSkillCooldownRemainingMs() map[string]float64 {
	if x != nil {
		return x.SkillCooldownRemainingMs
	}
	return nil
}

func (x *DungeonSnapshot) GetHasteRemainingMs() float64 {
	if x != nil {
		return x.HasteRemainingMs
	}
	return 0
}

func (x *DungeonSnapshot) GetHealthPotions() int32 {
	if x != nil {
		return x.HealthPotions
	}
	return 0
}

func (x *DungeonSnapshot) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

type DungeonSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Snapshot      *DungeonSnapshot       `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonSnapshotRequest) Reset() {
	*x = DungeonSnapshotRequest{}
	mi := &file_proto_dungeon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonSnapshotRequest) ProtoMessage() {}

func (x *DungeonSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DungeonSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{7}
}

func (x *DungeonSnapshotRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DungeonSnapshotRequest) GetSnapshot() *DungeonSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type DungeonSnapshotRelay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Snapshot      *DungeonSnapshot       `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonSnapshotRelay) Reset() {
	*x = DungeonSnapshotRelay{}
	mi := &file_proto_dungeon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonSnapshotRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonSnapshotRelay) ProtoMessage() {}

func (x *DungeonSnapshotRelay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonSnapshotRelay.ProtoReflect.Descriptor instead.
func (*DungeonSnapshotRelay) Descriptor() ([]byte, []int) {
	return file_proto_dungeon_proto_rawDescGZIP(), []int{8}
}

func (x *DungeonSnapshotRelay) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DungeonSnapshotRelay) GetSnapshot() *DungeonSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_proto_dungeon_proto protoreflect.FileDescriptor

const file_proto_dungeon_proto_rawDesc = "" +
	"\n" +
	"\x13proto/dungeon.proto\x12\x0earcade.dungeon\"P\n" +
	"\x0eDungeonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"s\n" +
	"\x0fDungeonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"\x1c\n" +
	"\n" +
	"DungeonAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"s\n" +
	"\x0eDungeonCommand\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x17\n" +
	"\adrop_id\x18\x03 \x01(\tR\x06dropId\x12\x19\n" +
	"\bchest_id\x18\x04 \x01(\tR\achestId\"j\n" +
	"\x15DungeonCommandRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x128\n" +
	"\acommand\x18\x02 \x01(\v2\x1e.arcade.dungeon.DungeonCommandR\acommand\"l\n" +
	"\x13DungeonCommandRelay\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x128\n" +
	"\acommand\x18\x02 \x01(\v2\x1e.arcade.dungeon.DungeonCommandR\acommand\"\xf5\x04\n" +
	"\x0fDungeonSnapshot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06facing\x18\x06 \x01(\tR\x06facing\x12\x16\n" +
	"\x06moving\x18\a \x01(\bR\x06moving\x12\x1c\n" +
	"\tattacking\x18\b \x01(\bR\tattacking\x12\x12\n" +
	"\x04dead\x18\t \x01(\bR\x04dead\x123\n" +
	"\x16last_attack_elapsed_ms\x18\n" +
	" \x01(\x01R\x13lastAttackElapsedMs\x125\n" +
	"\x17last_contact_elapsed_ms\x18\v \x01(\x01R\x14lastContactElapsedMs\x12|\n" +
	"\x1bskill_cooldown_remaining_ms\x18\f \x03(\v2=.arcade.dungeon.DungeonSnapshot.SkillCooldownRemainingMsEntryR\x18skillCooldownRemainingMs\x12,\n" +
	"\x12haste_remaining_ms\x18\r \x01(\x01R\x10hasteRemainingMs\x12%\n" +
	"\x0ehealth_potions\x18\x0e \x01(\x05R\rhealthPotions\x12\x1d\n" +
	"\n" +
	"state_json\x18\x0f \x01(\tR\tstateJson\x1aK\n" +
	"\x1dSkillCooldownRemainingMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"n\n" +
	"\x16DungeonSnapshotRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12;\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1f.arcade.dungeon.DungeonSnapshotR\bsnapshot\"p\n" +
	"\x14DungeonSnapshotRelay\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12;\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1f.arcade.dungeon.DungeonSnapshotR\bsnapshotB'Z%github.com/wonli/arcade/server;serverb\x06proto3"

var (
	file_proto_dungeon_proto_rawDescOnce sync.Once
	file_proto_dungeon_proto_rawDescData []byte
)

func file_proto_dungeon_proto_rawDescGZIP() []byte {
	file_proto_dungeon_proto_rawDescOnce.Do(func() {
		file_proto_dungeon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dungeon_proto_rawDesc), len(file_proto_dungeon_proto_rawDesc)))
	})
	return file_proto_dungeon_proto_rawDescData
}

var file_proto_dungeon_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_dungeon_proto_goTypes = []any{
	(*DungeonRequest)(nil),         // 0: arcade.dungeon.DungeonRequest
	(*DungeonResponse)(nil),        // 1: arcade.dungeon.DungeonResponse
	(*DungeonAck)(nil),             // 2: arcade.dungeon.DungeonAck
	(*DungeonCommand)(nil),         // 3: arcade.dungeon.DungeonCommand
	(*DungeonCommandRequest)(nil),  // 4: arcade.dungeon.DungeonCommandRequest
	(*DungeonCommandRelay)(nil),    // 5: arcade.dungeon.DungeonCommandRelay
	(*DungeonSnapshot)(nil),        // 6: arcade.dungeon.DungeonSnapshot
	(*DungeonSnapshotRequest)(nil), // 7: arcade.dungeon.DungeonSnapshotRequest
	(*DungeonSnapshotRelay)(nil),   // 8: arcade.dungeon.DungeonSnapshotRelay
	nil,                            // 9: arcade.dungeon.DungeonSnapshot.SkillCooldownRemainingMsEntry
}
var file_proto_dungeon_proto_depIdxs = []int32{
	3, // 0: arcade.dungeon.DungeonCommandRequest.command:type_name -> arcade.dungeon.DungeonCommand
	3, // 1: arcade.dungeon.DungeonCommandRelay.command:type_name -> arcade.dungeon.DungeonCommand
	9, // 2: arcade.dungeon.DungeonSnapshot.skill_cooldown_remaining_ms:type_name -> arcade.dungeon.DungeonSnapshot.SkillCooldownRemainingMsEntry
	6, // 3: arcade.dungeon.DungeonSnapshotRequest.snapshot:type_name -> arcade.dungeon.DungeonSnapshot
	6, // 4: arcade.dungeon.DungeonSnapshotRelay.snapshot:type_name -> arcade.dungeon.DungeonSnapshot
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_dungeon_proto_init() }
func file_proto_dungeon_proto_init() {
	if File_proto_dungeon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dungeon_proto_rawDesc), len(file_proto_dungeon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dungeon_proto_goTypes,
		DependencyIndexes: file_proto_dungeon_proto_depIdxs,
		MessageInfos:      file_proto_dungeon_proto_msgTypes,
	}.Build()
	File_proto_dungeon_proto = out.File
	file_proto_dungeon_proto_goTypes = nil
	file_proto_dungeon_proto_depIdxs = nil
}
